/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Parlant from "../../../../api/index";
import * as core from "../../../../core";
import { Relationship } from "../../../types/Relationship";
export declare const Response: core.serialization.Schema<serializers.relationships.list.Response.Raw, Parlant.Relationship[]>;
export declare namespace Response {
    type Raw = Relationship.Raw[];
}
