/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as Parlant from "../../../index";
export declare namespace Capabilities {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Capabilities {
    protected readonly _options: Capabilities.Options;
    constructor(_options: Capabilities.Options);
    /**
     * Retrieves a list of all capabilities in the system.
     *
     * Returns an empty list if no capabilities exist.
     * Capabilities are returned in no guaranteed order.
     *
     * @param {Parlant.CapabilitiesListRequest} request
     * @param {Capabilities.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.capabilities.list()
     */
    list(request?: Parlant.CapabilitiesListRequest, requestOptions?: Capabilities.RequestOptions): Promise<Parlant.Capability[]>;
    /**
     * Creates a new capability in the system.
     *
     * The capability will be initialized with the provided title, description, signals, and optional tags.
     * A unique identifier will be automatically generated.
     *
     * Default behaviors:
     * - `signals` defaults to an empty list if not provided
     *
     * @param {Parlant.CapabilityCreationParams} request
     * @param {Capabilities.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.capabilities.create({
     *         title: "Provide Replacement Phone",
     *         description: "Provide a replacement phone when a customer needs repair for their phone.",
     *         signals: ["My phone is broken", "I need a replacement while my phone is being repaired"],
     *         tags: ["tag1", "tag2"]
     *     })
     */
    create(request: Parlant.CapabilityCreationParams, requestOptions?: Capabilities.RequestOptions): Promise<Parlant.Capability>;
    /**
     * Retrieves details of a specific capability by ID.
     *
     * Returns the complete capability object.
     *
     * @param {string} capabilityId - Unique identifier for the capability
     * @param {Capabilities.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.capabilities.retrieve("cap_123abc")
     */
    retrieve(capabilityId: string, requestOptions?: Capabilities.RequestOptions): Promise<Parlant.Capability>;
    /**
     * Deletes a capability from the system.
     *
     * Deleting a non-existent capability will return 404.
     * No content will be returned from a successful deletion.
     *
     * @param {string} capabilityId - Unique identifier for the capability
     * @param {Capabilities.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.capabilities.delete("cap_123abc")
     */
    delete(capabilityId: string, requestOptions?: Capabilities.RequestOptions): Promise<void>;
    /**
     * Updates an existing capability's attributes.
     *
     * Only the provided attributes will be updated; others will remain unchanged.
     * The capability's ID and creation timestamp cannot be modified.
     *
     * @param {string} capabilityId - Unique identifier for the capability
     * @param {Parlant.CapabilityUpdateParams} request
     * @param {Capabilities.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.capabilities.update("cap_123abc", {
     *         title: "Provide Replacement Phone",
     *         description: "Provide a replacement phone when a customer needs repair for their phone.",
     *         signals: ["My phone is broken", "I need a replacement while my phone is being repaired"]
     *     })
     */
    update(capabilityId: string, request?: Parlant.CapabilityUpdateParams, requestOptions?: Capabilities.RequestOptions): Promise<Parlant.Capability>;
}
