/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         sourceGuideline: "gid_123",
 *         targetTag: "tid_456",
 *         kind: "entailment"
 *     }
 */
export interface RelationshipCreationParams {
    /** Unique identifier for the guideline */
    sourceGuideline?: string;
    /** Unique identifier for the tag */
    sourceTag?: string;
    sourceTool?: Parlant.ToolId;
    /** Unique identifier for the guideline */
    targetGuideline?: string;
    /** Unique identifier for the tag */
    targetTag?: string;
    targetTool?: Parlant.ToolId;
    kind: Parlant.RelationshipKindDto;
}
