/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface AgentMessageGuideline {
    /** A single action that explains what to say; i.e. "Tell the customer that you are thinking and will be right back with an answer." */
    action: string;
    rationale?: Parlant.AgentMessageGuidelineRationaleDto;
}
