/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Defines the rationale for the guideline
 */
export type AgentMessageGuidelineRationaleDto = "unspecified" | "buy_time" | "follow_up";
export declare const AgentMessageGuidelineRationaleDto: {
    readonly Unspecified: "unspecified";
    readonly BuyTime: "buy_time";
    readonly FollowUp: "follow_up";
};
