/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating an existing agent's tags.
 */
export interface AgentTagUpdateParams {
    /** List of tag IDs to add to the agent */
    add?: string[];
    /** List of tag IDs to remove from the agent */
    remove?: string[];
}
