"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AgentMessageGuidelineRationaleDto = void 0;
exports.AgentMessageGuidelineRationaleDto = {
    Unspecified: "unspecified",
    BuyTime: "buy_time",
    FollowUp: "follow_up",
};
