/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * An agent is a specialized AI personality crafted for a specific service role.
 *
 * Agents form the basic unit of conversational customization: all behavioral configurations
 * are made at the agent level.
 *
 * Use this model for representing complete agent information in API responses.
 */
export interface Agent {
    /** Unique identifier for the agent */
    id: string;
    /** The display name of the agent, mainly for management purposes */
    name: string;
    /** Detailed description of the agent's purpose and capabilities */
    description?: string;
    /** Maximum number of processing iterations the agent can perform per request */
    maxEngineIterations?: number;
    compositionMode: Parlant.CompositionModeDto;
    messageOutputMode: Parlant.MessageOutputModeDto;
    /** List of tag IDs associated with the agent */
    tags?: string[];
}
