/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating the metadata of a canned response.
 */
export interface CannedResponseMetadataUpdateParams {
    /** Additional metadata associated with the canned response. */
    set?: Record<string, unknown>;
    /** Metadata keys to remove from the canned response */
    unset?: string[];
}
