/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating an existing capability's tags.
 */
export interface CapabilityTagUpdateParams {
    /** List of tag IDs to add to the capability */
    add?: string[];
    /** List of tag IDs to remove from the capability */
    remove?: string[];
}
