/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A capability represents a functional feature or skill of the agent.
 */
export interface Capability {
    /** Unique identifier for the capability */
    id: string;
    /** The title of the capability */
    title: string;
    /** Detailed description of the capability's purpose */
    description: string;
    /** Example signals that this capability can handle */
    signals: string[];
    /** List of tag IDs associated with the capability */
    tags?: string[];
}
