/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Defines the composition mode for an entity.
 *
 * Available options:
 * - fluid
 * - canned_fluid
 * - composited_canned
 * - strict_canned
 */
export type CompositionModeDto = "fluid" | "canned_fluid" | "composited_canned" | "strict_canned";
export declare const CompositionModeDto: {
    readonly Fluid: "fluid";
    readonly CannedFluid: "canned_fluid";
    readonly CompositedCanned: "composited_canned";
    readonly StrictCanned: "strict_canned";
};
