/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Tracking for message consumption state.
 */
export interface ConsumptionOffsets {
    /** Latest event offset processed by the client */
    client?: number;
}
