/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating consumption offsets.
 */
export interface ConsumptionOffsetsUpdateParams {
    /** Latest event offset processed by the client */
    client?: number;
}
