/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Represents the actual stored value for a specific customer's or tag's context.
 *
 * This could be their subscription details, feature usage history,
 * preferences, or any other customer or tag information that helps
 * personalize the agent's responses.
 */
export interface ContextVariableValue {
    /** Unique identifier for the variable value */
    id: string;
    /** Timestamp of the last modification */
    lastModified: Date;
    data?: unknown;
}
