/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Represents a context variable type.
 */
export interface ContextVariable {
    /** Unique identifier for the context variable */
    id: string;
    /** Name of the context variable */
    name: string;
    /** Description of the context variable's purpose */
    description?: string;
    toolId?: Parlant.ToolId;
    /** Cron expression defining the freshness rules */
    freshnessRules?: string;
    /** List of tags associated with the context variable */
    tags?: string[];
}
