/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating the tags of an existing context variable.
 */
export interface ContextVariableTagsUpdateParams {
    /** List of tag IDs to add to the context variable */
    add?: string[];
    /** List of tag IDs to remove from the context variable */
    remove?: string[];
}
