/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The criticality level of a guideline.
 */
export type CriticalityDto = "low" | "medium" | "high";
export declare const CriticalityDto: {
    readonly Low: "low";
    readonly Medium: "medium";
    readonly High: "high";
};
