"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CriticalityDto = void 0;
exports.CriticalityDto = {
    Low: "low",
    Medium: "medium",
    High: "high",
};
