/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating a customer's extra metadata.
 */
export interface CustomerMetadataUpdateParams {
    /** Key-value pairs (`str: str`) to describe the customer */
    set?: Record<string, string | undefined>;
    /** Extra metadata keys to remove */
    unset?: string[];
}
