/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating a customer's tags.
 *
 * Allows adding new tags to and removing existing tags from a customer.
 * Both operations can be performed in a single request.
 */
export interface CustomerTagUpdateParams {
    /** Optional collection of tag ids to add to the customer's tags */
    add?: string[];
    /** Optional collection of tag ids to remove from the customer's tags */
    remove?: string[];
}
