/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Current state of an evaluation task
 */
export type EvaluationStatusDto = "pending" | "running" | "completed" | "failed";
export declare const EvaluationStatusDto: {
    readonly Pending: "pending";
    readonly Running: "running";
    readonly Completed: "completed";
    readonly Failed: "failed";
};
