"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventKindDto = void 0;
exports.EventKindDto = {
    Message: "message",
    Tool: "tool",
    Status: "status",
    Custom: "custom",
};
