/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Source of an event in the session.
 *
 * Identifies who or what generated the event.
 */
export type EventSourceDto = "customer" | "customer_ui" | "human_agent" | "human_agent_on_behalf_of_ai_agent" | "ai_agent" | "system";
export declare const EventSourceDto: {
    readonly Customer: "customer";
    readonly CustomerUi: "customer_ui";
    readonly HumanAgent: "human_agent";
    readonly HumanAgentOnBehalfOfAiAgent: "human_agent_on_behalf_of_ai_agent";
    readonly AiAgent: "ai_agent";
    readonly System: "system";
};
