"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventSourceDto = void 0;
exports.EventSourceDto = {
    Customer: "customer",
    CustomerUi: "customer_ui",
    HumanAgent: "human_agent",
    HumanAgentOnBehalfOfAiAgent: "human_agent_on_behalf_of_ai_agent",
    AiAgent: "ai_agent",
    System: "system",
};
