/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Type of event in a session.
 *
 * Represents different types of interactions that can occur within a conversation.
 */
export type EventKindDto = "message" | "tool" | "status" | "custom";
export declare const EventKindDto: {
    readonly Message: "message";
    readonly Tool: "tool";
    readonly Status: "status";
    readonly Custom: "custom";
};
