/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Represents a single event within a session.
 */
export interface Event {
    /** Unique identifier for the event */
    id: string;
    source: Parlant.EventSourceDto;
    kind: Parlant.EventKindDto;
    /** Sequential position of the event in the session */
    offset: number;
    /** UTC timestamp of when the event was created */
    creationUtc: Date;
    /** ID linking related events together */
    traceId: string;
    /** ID linking related events together */
    correlationId: string;
    data?: unknown;
    /** Metadata associated with the event */
    metadata: Record<string, unknown>;
    deleted: boolean;
}
