"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GuidelinePayloadOperationDto = void 0;
exports.GuidelinePayloadOperationDto = {
    Add: "add",
    Update: "update",
};
