/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Payload data for a Guideline operation
 */
export interface GuidelinePayload {
    content: Parlant.GuidelineContent;
    toolIds: Parlant.ToolId[];
    operation: Parlant.GuidelinePayloadOperationDto;
    /** Unique identifier for the guideline */
    updatedId?: string;
    /** Whether the action proposition is enabled */
    actionProposition?: boolean;
    /** Properties proposition */
    propertiesProposition?: boolean;
    /** Journey step proposition */
    journeyNodeProposition?: boolean;
}
