/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The kind of operation that should be performed on the payload.
 */
export type GuidelinePayloadOperationDto = "add" | "update";
export declare const GuidelinePayloadOperationDto: {
    readonly Add: "add";
    readonly Update: "update";
};
