/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Represents a guideline.
 */
export interface Guideline {
    /** Unique identifier for the guideline */
    id: string;
    /** If this condition is satisfied, the action will be performed */
    condition: string;
    /** This action will be performed if the condition is satisfied */
    action?: string;
    /** Optional description providing additional context for the guideline */
    description?: string;
    /** The criticality level of the guideline */
    criticality?: Parlant.CriticalityDto;
    /** Whether the guideline is enabled */
    enabled?: boolean;
    /** The tags associated with the guideline */
    tags: string[];
    /** Metadata for the guideline */
    metadata: Record<string, unknown>;
    compositionMode?: Parlant.CompositionModeDto;
    track?: boolean;
    /** The labels associated with the guideline */
    labels?: string[];
    priority?: number;
}
