/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Represention of a guideline with a condition-action pair.
 *
 * This model defines a structure for guidelines where specific actions should be taken
 * when certain conditions are met. It follows a simple "if condition then action" pattern.
 */
export interface GuidelineContent {
    /** If this condition is satisfied, the action will be performed */
    condition: string;
    /** This action will be performed if the condition is satisfied */
    action?: string;
}
