/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * A Guideline with its relationships and tool associations.
 */
export interface GuidelineWithRelationshipsAndToolAssociations {
    guideline: Parlant.Guideline;
    relationships: Parlant.Relationship[];
    toolAssociations: Parlant.GuidelineToolAssociation[];
}
