/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Parameters for adding/removing tool associations.
 */
export interface GuidelineToolAssociationUpdateParams {
    add?: Parlant.ToolId[];
    remove?: Parlant.ToolId[];
}
