/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Evaluation results for a Guideline, including action propositions
 */
export interface GuidelineInvoiceData {
    /** Proposed action proposition */
    actionProposition?: string;
    propertiesProposition?: Record<string, unknown>;
}
