/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Represents an association between a Guideline and a Tool, enabling automatic tool invocation
 * when the Guideline's conditions are met.
 */
export interface GuidelineToolAssociation {
    /** Unique identifier for the association between a tool and a guideline */
    id: string;
    /** Unique identifier for the guideline */
    guidelineId: string;
    toolId: Parlant.ToolId;
}
