/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating the labels of an existing guideline.
 */
export interface GuidelineLabelsUpdateParams {
    /** The labels associated with the guideline */
    upsert?: string[];
    /** The labels associated with the guideline */
    remove?: string[];
}
