/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating the tags of an existing guideline.
 */
export interface GuidelineTagsUpdateParams {
    /** List of tag IDs to add to the guideline */
    add?: string[];
    /** List of tag IDs to remove from the guideline */
    remove?: string[];
}
