/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Represents the result of evaluating a single payload in an evaluation task.
 *
 * An invoice is a comprehensive record of the evaluation results for a single payload.
 */
export interface Invoice {
    payload: Parlant.Payload;
    /** Checksum of the invoice content */
    checksum: string;
    /** Whether the evaluation task the invoice represents has been approved */
    approved: boolean;
    data?: Parlant.InvoiceData;
    /** Error message if the evaluation failed */
    error?: string;
}
