/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Contains the relevant invoice data.
 *
 * At this point only `guideline` is supported.
 */
export interface InvoiceData {
    guideline?: Parlant.GuidelineInvoiceData;
}
