/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating an existing journey's tags.
 */
export interface JourneyTagUpdateParams {
    /** List of tag IDs to add to the journey */
    add?: string[];
    /** List of tag IDs to remove from the journey */
    remove?: string[];
}
