/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating an existing journey's labels.
 */
export interface JourneyLabelsUpdateParams {
    /** Labels associated with the journey */
    upsert?: string[];
    /** Labels associated with the journey */
    remove?: string[];
}
