/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * A journey represents a guided interaction path for specific user scenarios.
 *
 * Each journey is triggered by a condition and contains steps to guide the interaction.
 */
export interface Journey {
    /** Unique identifier for the journey */
    id: string;
    /** The title of the journey */
    title: string;
    description: string;
    conditions: string[];
    /** List of tag IDs associated with the journey */
    tags?: string[];
    compositionMode?: Parlant.CompositionModeDto;
    /** Labels associated with the journey */
    labels?: string[];
    priority?: number;
}
