/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating an existing journey's conditions.
 */
export interface JourneyConditionUpdateParams {
    /** List of guideline IDs to add to the journey */
    add?: string[];
    /** List of guideline IDs to remove from the journey */
    remove?: string[];
}
