/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Configuration parameters for MCP-based service integration.
 *
 * MCP services use the MCP protocol, which enables advanced features
 * and supports a wide variety of variable types. It is widely adopted by third parties worldwide.
 */
export interface McpServiceParams {
    /** Base URL for the service. Must include http:// or https:// scheme. */
    url: string;
}
