/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Defines how the agent outputs messages.
 *
 * Available options:
 * - block: Full message is sent at once (default behavior)
 * - stream: Message is streamed token by token
 */
export type MessageOutputModeDto = "block" | "stream";
export declare const MessageOutputModeDto: {
    readonly Block: "block";
    readonly Stream: "stream";
};
