"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessageOutputModeDto = void 0;
exports.MessageOutputModeDto = {
    Block: "block",
    Stream: "stream",
};
