/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Paginated response for customers
 */
export interface PaginatedCustomers {
    items: Parlant.Customer[];
    totalCount: number;
    hasMore: boolean;
    nextCursor?: string;
}
