/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Represents the participant information in a message event.
 */
export interface Participant {
    id?: string;
    /** Name to display for the participant */
    displayName: string;
}
