/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface Payload {
    kind: Parlant.PayloadKindDto;
    guideline?: Parlant.GuidelinePayload;
}
