/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The kind of payload.
 *
 * At this point only `"guideline"` is supported.
 */
export type PayloadKindDto = "guideline";
