"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RelationshipKindDto = void 0;
exports.RelationshipKindDto = {
    Entailment: "entailment",
    Priority: "priority",
    Dependency: "dependency",
    Disambiguation: "disambiguation",
    Overlap: "overlap",
    Reevaluation: "reevaluation",
};
