/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Configuration parameters for SDK-based service integration.
 *
 * SDK services must implement the Parlant SDK protocol for advanced features
 * like streaming and bidirectional communication.
 */
export interface SdkServiceParams {
    /** Base URL for the service. Must include http:// or https:// scheme. */
    url: string;
}
