/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Details about an integrated service and its available tools.
 *
 * Services can be either SDK-based for advanced features or OpenAPI-based
 * for simpler integrations. The tools list is only included when retrieving
 * a specific service, not in list operations.
 */
export interface Service {
    /** Name of the service */
    name: string;
    kind: Parlant.ToolServiceKindDto;
    /** Base URL where the service is hosted */
    url: string;
    /** List of tools provided by this service. Only included when retrieving a specific service. */
    tools?: Parlant.Tool[];
}
