/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Paginated response for sessions
 */
export interface SessionListing {
    items: Parlant.Session[];
    totalCount: number;
    hasMore: boolean;
    nextCursor?: string;
}
