/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Type of status in a session.
 */
export type SessionStatusDto = "acknowledged" | "cancelled" | "processing" | "ready" | "typing" | "error";
export declare const SessionStatusDto: {
    readonly Acknowledged: "acknowledged";
    readonly Cancelled: "cancelled";
    readonly Processing: "processing";
    readonly Ready: "ready";
    readonly Typing: "typing";
    readonly Error: "error";
};
