/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating a session's metadata.
 */
export interface SessionMetadataUpdateParams {
    /** Metadata for the session */
    set?: Record<string, unknown>;
    /** Metadata keys to remove from the session */
    unset?: string[];
}
