/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating a session's labels.
 */
export interface SessionLabelsUpdateParams {
    /** Labels associated with the session */
    upsert?: string[];
    /** Labels associated with the session */
    remove?: string[];
}
