"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SessionStatusDto = void 0;
exports.SessionStatusDto = {
    Acknowledged: "acknowledged",
    Cancelled: "cancelled",
    Processing: "processing",
    Ready: "ready",
    Typing: "typing",
    Error: "error",
};
