/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Defines the reason for the action
 */
export type SessionModeDto = "auto" | "manual";
export declare const SessionModeDto: {
    readonly Auto: "auto";
    readonly Manual: "manual";
};
