"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SortDirectionDto = void 0;
exports.SortDirectionDto = {
    Asc: "asc",
    Desc: "desc",
};
