/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The direction to sort results.
 */
export type SortDirectionDto = "asc" | "desc";
export declare const SortDirectionDto: {
    readonly Asc: "asc";
    readonly Desc: "desc";
};
