/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Represents a tag in the system.
 *
 * Tags can be used to categorize and label various resources like customers, sessions,
 * or content. They provide a flexible way to organize and filter data.
 */
export interface Tag {
    /** Unique identifier for the tag */
    id: string;
    /** Human-readable name for the tag, used for display and organization */
    name: string;
}
