/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Represents a glossary term associated with an agent.
 *
 * Use this model for representing complete term information in API responses.
 */
export interface Term {
    /** Unique identifier for the term */
    id: string;
    /** The name of the term, e.g., 'Gas' in blockchain. */
    name: string;
    /** A detailed description of the term */
    description: string;
    /** A list of synonyms for the term, including alternate contexts if applicable. */
    synonyms?: string[];
    /** List of tag IDs associated with the term */
    tags: string[];
}
