/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating the tags of an existing glossary term.
 */
export interface TermTagsUpdateParams {
    /** List of tag IDs to add to the term */
    add?: string[];
    /** List of tag IDs to remove from the term */
    remove?: string[];
}
