"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ToolParameterTypeDto = void 0;
exports.ToolParameterTypeDto = {
    String: "string",
    Number: "number",
    Integer: "integer",
    Boolean: "boolean",
    Array: "array",
};
