/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Represents a single function provided by an integrated service.
 *
 * Tools are the primary way for agents to interact with external services.
 * Each tool has defined parameters and can be invoked when those parameters
 * are satisfied.
 */
export interface Tool {
    /** UTC timestamp when the tool was first registered with the system */
    creationUtc: Date;
    /** Name of the tool */
    name: string;
    /** Detailed description of the tool's purpose and behavior */
    description: string;
    /** Dictionary mapping parameter names to their definitions */
    parameters: Record<string, Parlant.ToolParameter>;
    /** List of parameter names that must be provided when calling the tool */
    required: string[];
}
