/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Defines a parameter that can be passed to a tool.
 *
 * Parameters can have different types with optional constraints like enums.
 * Each parameter can include a description to help users understand its purpose.
 */
export interface ToolParameter {
    type: Parlant.ToolParameterTypeDto;
    /** Detailed description of what the parameter does and how it should be used */
    description?: string;
    /** List of allowed values for string or integer parameters. If provided, the parameter value must be one of these options. */
    enum?: Parlant.ToolParameterDtoEnumItem[];
}
