/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The supported data types for tool parameters.
 *
 * Each type corresponds to a specific JSON Schema type and validation rules.
 */
export type ToolParameterTypeDto = "string" | "number" | "integer" | "boolean" | "array";
export declare const ToolParameterTypeDto: {
    readonly String: "string";
    readonly Number: "number";
    readonly Integer: "integer";
    readonly Boolean: "boolean";
    readonly Array: "array";
};
