/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Tool identifier associated with this variable
 */
export interface ToolId {
    /** Name of the service */
    serviceName: string;
    /** Name of the tool */
    toolName: string;
}
