/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface ValidationError {
    loc: Parlant.ValidationErrorLocItem[];
    msg: string;
    type: string;
    input?: unknown;
    ctx?: Record<string, unknown>;
}
