/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Parlant from "../../../../api/index";
import * as core from "../../../../core";
import { Guideline } from "../../../types/Guideline";
export declare const Response: core.serialization.Schema<serializers.guidelines.list.Response.Raw, Parlant.Guideline[]>;
export declare namespace Response {
    type Raw = Guideline.Raw[];
}
