/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const TagCreationParams: core.serialization.Schema<serializers.TagCreationParams.Raw, Parlant.TagCreationParams>;
export declare namespace TagCreationParams {
    interface Raw {
        name: string;
    }
}
