/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const TagUpdateParams: core.serialization.Schema<serializers.TagUpdateParams.Raw, Parlant.TagUpdateParams>;
export declare namespace TagUpdateParams {
    interface Raw {
        name: string;
    }
}
