/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface GlossaryListTermsRequest {
    /**
     * Filter terms by tag ID
     */
    tagId?: string;
}
