/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         name: "Gas",
 *         description: "A unit in Ethereum that measures the computational effort to execute transactions or smart contracts",
 *         synonyms: ["Transaction Fee", "Blockchain Fuel"],
 *         tags: {
 *             add: ["tag1", "tag2"],
 *             remove: ["tag3", "tag4"]
 *         }
 *     }
 */
export interface TermUpdateParams {
    /** The name of the term, e.g., 'Gas' in blockchain. */
    name?: string;
    /** A detailed description of the term */
    description?: string;
    /** A list of synonyms for the term, including alternate contexts if applicable. */
    synonyms?: string[];
    tags?: Parlant.TermTagsUpdateParams;
}
