/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Parlant from "../../../../api/index";
import * as core from "../../../../core";
import { Capability } from "../../../types/Capability";
export declare const Response: core.serialization.Schema<serializers.capabilities.list.Response.Raw, Parlant.Capability[]>;
export declare namespace Response {
    type Raw = Capability.Raw[];
}
