"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ParlantTimeoutError = void 0;
class ParlantTimeoutError extends Error {
    constructor(message) {
        super(message);
        Object.setPrototypeOf(this, ParlantTimeoutError.prototype);
    }
}
exports.ParlantTimeoutError = ParlantTimeoutError;
