/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Parlant from "../../../../api/index";
import * as core from "../../../../core";
import { Service } from "../../../types/Service";
export declare const Response: core.serialization.Schema<serializers.services.list.Response.Raw, Parlant.Service[]>;
export declare namespace Response {
    type Raw = Service.Raw[];
}
