/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Parlant from "../../../../api/index";
import * as core from "../../../../core";
import { SessionListing } from "../../../types/SessionListing";
import { Session } from "../../../types/Session";
export declare const SessionsListResponse: core.serialization.Schema<serializers.SessionsListResponse.Raw, Parlant.SessionsListResponse>;
export declare namespace SessionsListResponse {
    type Raw = SessionListing.Raw | Session.Raw[];
}
