/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Parlant from "../../../../api/index";
import * as core from "../../../../core";
import { Tag } from "../../../types/Tag";
export declare const Response: core.serialization.Schema<serializers.tags.list.Response.Raw, Parlant.Tag[]>;
export declare namespace Response {
    type Raw = Tag.Raw[];
}
