/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Parlant from "../../../../api/index";
import * as core from "../../../../core";
import { ContextVariable } from "../../../types/ContextVariable";
export declare const Response: core.serialization.Schema<serializers.contextVariables.list.Response.Raw, Parlant.ContextVariable[]>;
export declare namespace Response {
    type Raw = ContextVariable.Raw[];
}
