/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as Parlant from "../../../index";
export declare namespace Tags {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Tags {
    protected readonly _options: Tags.Options;
    constructor(_options: Tags.Options);
    /**
     * Lists all tags in the system, optionally filtered by name.
     *
     * Returns an empty list if no tags exist or none match the filter.
     * Tags are returned in no particular order.
     *
     * @param {Parlant.TagsListRequest} request
     * @param {Tags.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.tags.list()
     */
    list(request?: Parlant.TagsListRequest, requestOptions?: Tags.RequestOptions): Promise<Parlant.Tag[]>;
    /**
     * Creates a new tag with the specified name.
     *
     * The tag ID is automatically generated and the creation timestamp is set to the current time.
     * Tag names must be unique and follow the kebab-case format.
     *
     * @param {Parlant.TagCreationParams} request
     * @param {Tags.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.tags.create({
     *         name: "premium-customer"
     *     })
     */
    create(request: Parlant.TagCreationParams, requestOptions?: Tags.RequestOptions): Promise<Parlant.Tag>;
    /**
     * Retrieves details of a specific tag by ID.
     *
     * Returns a 404 error if no tag exists with the specified ID.
     *
     * @param {string} tagId - Unique identifier for the tag to operate on
     * @param {Tags.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.tags.retrieve("tag_123xyz")
     */
    retrieve(tagId: string, requestOptions?: Tags.RequestOptions): Promise<Parlant.Tag>;
    /**
     * Permanently deletes a tag.
     *
     * This operation cannot be undone. Returns a 404 error if no tag exists with the specified ID.
     * Note that deleting a tag does not affect resources that were previously tagged with it.
     *
     * @param {string} tagId
     * @param {Tags.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.tags.delete("tag_id")
     */
    delete(tagId: string, requestOptions?: Tags.RequestOptions): Promise<void>;
    /**
     * Updates an existing tag's name.
     *
     * Only the name can be modified,
     * The tag's ID and creation timestamp cannot be modified.
     *
     * @param {string} tagId - Unique identifier for the tag to operate on
     * @param {Parlant.TagUpdateParams} request
     * @param {Tags.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.tags.update("tag_123xyz", {
     *         name: "enterprise-customer"
     *     })
     */
    update(tagId: string, request: Parlant.TagUpdateParams, requestOptions?: Tags.RequestOptions): Promise<Parlant.Tag>;
}
