/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const ContextVariableValueUpdateParams: core.serialization.Schema<serializers.ContextVariableValueUpdateParams.Raw, Parlant.ContextVariableValueUpdateParams>;
export declare namespace ContextVariableValueUpdateParams {
    interface Raw {
        data?: unknown;
    }
}
