/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { ToolId } from "../../../../types/ToolId";
import { ContextVariableTagsUpdateParams } from "../../../../types/ContextVariableTagsUpdateParams";
export declare const ContextVariableUpdateParams: core.serialization.Schema<serializers.ContextVariableUpdateParams.Raw, Parlant.ContextVariableUpdateParams>;
export declare namespace ContextVariableUpdateParams {
    interface Raw {
        name?: string | null;
        description?: string | null;
        tool_id?: ToolId.Raw | null;
        freshness_rules?: string | null;
        tags?: ContextVariableTagsUpdateParams.Raw | null;
    }
}
