/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         metadata: {
 *             set: {
 *                 "agent_id": "agent_123",
 *                 "category": "support",
 *                 "priority": "high"
 *             },
 *             unset: ["old_priority"]
 *         }
 *     }
 */
export interface EventUpdateParams {
    metadata?: Parlant.SessionMetadataUpdateParams;
}
