/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         kind: "message",
 *         source: "customer",
 *         message: "Hello, I need help with my order"
 *     }
 */
export interface EventCreationParams {
    /**
     * Content moderation level for the event
     */
    moderation?: Parlant.ModerationDto;
    kind: Parlant.EventKindDto;
    source: Parlant.EventSourceDto;
    /** Event payload data, format depends on kind */
    message?: string;
    data?: unknown;
    /** Metadata associated with the event */
    metadata?: Record<string, unknown>;
    guidelines?: Parlant.AgentMessageGuideline[];
    participant?: Parlant.Participant;
    status?: Parlant.SessionStatusDto;
}
