/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         agentId: "ag_123xyz",
 *         customerId: "cust_123xy",
 *         limit: 10,
 *         cursor: "AAABjnBU9gBl/0BQt1axI0VniQI="
 *     }
 */
export interface SessionsListRequest {
    agentId?: string;
    customerId?: string;
    labels?: string | string[];
    limit?: number;
    cursor?: string;
    sort?: Parlant.SortDirectionDto;
}
