/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface SessionsReadEventRequest {
    waitForCompletion?: boolean;
    waitForData?: number;
    sse?: boolean;
}
