/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         agentId: "ag_123xyz",
 *         customerId: "cust_123xy",
 *         title: "Product inquiry session",
 *         metadata: {
 *             "priority": "high",
 *             "project": "demo"
 *         },
 *         labels: ["vip", "priority"]
 *     }
 */
export interface SessionCreationParams {
    /**
     * Whether to allow the agent to send an initial greeting
     */
    allowGreeting?: boolean;
    /** Unique identifier for the agent associated with the session. */
    agentId: string;
    /**  ID of the customer this session belongs to. If not provided, a guest customer will be created. */
    customerId?: string;
    /** Descriptive title for the session */
    title?: string;
    /** Metadata for the session */
    metadata?: Record<string, unknown>;
    /** Labels associated with the session */
    labels?: string[];
}
