/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         minOffset: 0
 *     }
 */
export interface SessionsDeleteEventsRequest {
    /**
     * Only return events with offset >= this value
     */
    minOffset: number;
}
