/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Parlant from "../../../../api/index";
import * as core from "../../../../core";
import { Journey } from "../../../types/Journey";
export declare const Response: core.serialization.Schema<serializers.journeys.list.Response.Raw, Parlant.Journey[]>;
export declare namespace Response {
    type Raw = Journey.Raw[];
}
