/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         name: "Haxon",
 *         description: "Technical Support Assistant",
 *         maxEngineIterations: 3,
 *         compositionMode: "fluid",
 *         messageOutputMode: "block",
 *         tags: ["tag1", "tag2"]
 *     }
 */
export interface AgentCreationParams {
    /** The display name of the agent, mainly for management purposes */
    name: string;
    /** Unique identifier for the agent */
    id?: string;
    /** Detailed description of the agent's purpose and capabilities */
    description?: string;
    /** Maximum number of processing iterations the agent can perform per request */
    maxEngineIterations?: number;
    compositionMode?: Parlant.CompositionModeDto;
    messageOutputMode?: Parlant.MessageOutputModeDto;
    /** List of tag IDs associated with the agent */
    tags?: string[];
}
