"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventUpdateParams = exports.EventCreationParams = exports.SessionUpdateParams = exports.SessionCreationParams = void 0;
var SessionCreationParams_1 = require("./SessionCreationParams");
Object.defineProperty(exports, "SessionCreationParams", { enumerable: true, get: function () { return SessionCreationParams_1.SessionCreationParams; } });
var SessionUpdateParams_1 = require("./SessionUpdateParams");
Object.defineProperty(exports, "SessionUpdateParams", { enumerable: true, get: function () { return SessionUpdateParams_1.SessionUpdateParams; } });
var EventCreationParams_1 = require("./EventCreationParams");
Object.defineProperty(exports, "EventCreationParams", { enumerable: true, get: function () { return EventCreationParams_1.EventCreationParams; } });
var EventUpdateParams_1 = require("./EventUpdateParams");
Object.defineProperty(exports, "EventUpdateParams", { enumerable: true, get: function () { return EventUpdateParams_1.EventUpdateParams; } });
