/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const SessionCreationParams: core.serialization.Schema<serializers.SessionCreationParams.Raw, Omit<Parlant.SessionCreationParams, "allowGreeting">>;
export declare namespace SessionCreationParams {
    interface Raw {
        agent_id: string;
        customer_id?: string | null;
        title?: string | null;
        metadata?: Record<string, unknown> | null;
        labels?: string[] | null;
    }
}
