/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { ConsumptionOffsetsUpdateParams } from "../../../../types/ConsumptionOffsetsUpdateParams";
import { SessionModeDto } from "../../../../types/SessionModeDto";
import { SessionMetadataUpdateParams } from "../../../../types/SessionMetadataUpdateParams";
import { SessionLabelsUpdateParams } from "../../../../types/SessionLabelsUpdateParams";
export declare const SessionUpdateParams: core.serialization.Schema<serializers.SessionUpdateParams.Raw, Parlant.SessionUpdateParams>;
export declare namespace SessionUpdateParams {
    interface Raw {
        consumption_offsets?: ConsumptionOffsetsUpdateParams.Raw | null;
        title?: string | null;
        mode?: SessionModeDto.Raw | null;
        customer_id?: string | null;
        agent_id?: string | null;
        metadata?: SessionMetadataUpdateParams.Raw | null;
        labels?: SessionLabelsUpdateParams.Raw | null;
    }
}
