/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Parlant from "../../../../api/index";
import * as core from "../../../../core";
import { CannedResponse } from "../../../types/CannedResponse";
export declare const Response: core.serialization.Schema<serializers.cannedResponses.list.Response.Raw, Parlant.CannedResponse[]>;
export declare namespace Response {
    type Raw = CannedResponse.Raw[];
}
