/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface JourneysListRequest {
    /**
     * The tag ID to filter journeys by
     */
    tagId?: string;
}
