/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         title: "Customer Onboarding",
 *         description: "1. Customer wants to lock their card\n2. Customer reports that their card doesn't work\n3. Customer suspects their card has been stolen"
 *     }
 */
export interface JourneyUpdateParams {
    /** The title of the journey */
    title?: string;
    description?: string;
    conditions?: Parlant.JourneyConditionUpdateParams;
    tags?: Parlant.JourneyTagUpdateParams;
    compositionMode?: Parlant.CompositionModeDto;
    labels?: Parlant.JourneyLabelsUpdateParams;
    priority?: number;
}
