/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         title: "Customer Onboarding",
 *         description: "1. Customer wants to lock their card\n2. Customer reports that their card doesn't work\n3. Customer suspects their card has been stolen",
 *         conditions: ["customer needs unlocking their card", "customer needs help with card"],
 *         id: "IUCGT-lvpS",
 *         tags: ["tag1", "tag2"],
 *         labels: ["vip", "priority"]
 *     }
 */
export interface JourneyCreationParams {
    /** The title of the journey */
    title: string;
    description: string;
    conditions: string[];
    /** Unique identifier for the journey */
    id?: string;
    /** List of tag IDs associated with the journey */
    tags?: string[];
    compositionMode?: Parlant.CompositionModeDto;
    /** Labels associated with the journey */
    labels?: string[];
    priority?: number;
}
