/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as Parlant from "../../../index";
export declare namespace Services {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Services {
    protected readonly _options: Services.Options;
    constructor(_options: Services.Options);
    /**
     * Get details about a specific service including all its tools.
     *
     * The response includes:
     * - Basic service information (name, kind, URL)
     * - Complete list of available tools
     * - Parameter definitions for each tool
     *
     * Notes:
     * - Tools list may be empty if service is still initializing
     * - Parameters marked as required must be provided when using a tool
     * - Enum parameters restrict inputs to the listed values
     *
     * @param {string} name - Unique identifier for the service
     * @param {Services.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     * @throws {@link Parlant.ServiceUnavailableError}
     *
     * @example
     *     await client.services.retrieve("email-service")
     */
    retrieve(name: string, requestOptions?: Services.RequestOptions): Promise<Parlant.Service>;
    /**
     * Creates a new service or updates an existing one.
     *
     * For SDK services:
     * - Target server must implement the Parlant SDK protocol
     * - Supports bidirectional communication and streaming
     *
     * For OpenAPI services:
     * - Spec must be accessible and compatible with OpenAPI 3.0
     * - Limited to request/response patterns
     *
     * Common requirements:
     * - Service names must be unique and kebab-case
     * - URLs must include http:// or https:// scheme
     * - Updates cause brief service interruption while reconnecting
     *
     * @param {string} name - Unique identifier for the service
     * @param {Parlant.ServiceUpdateParams} request
     * @param {Services.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.services.createOrUpdate("email-service", {
     *         kind: "openapi",
     *         openapi: {
     *             url: "https://email-service.example.com/api/v1",
     *             source: "https://email-service.example.com/api/openapi.json"
     *         }
     *     })
     */
    createOrUpdate(name: string, request: Parlant.ServiceUpdateParams, requestOptions?: Services.RequestOptions): Promise<Parlant.Service>;
    /**
     * Removes a service integration.
     *
     * Effects:
     * - Active connections are terminated immediately
     * - Service tools become unavailable to agents
     * - Historical data about tool usage is preserved
     * - Running operations may fail
     *
     * @param {string} name - Unique identifier for the service
     * @param {Services.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.services.delete("email-service")
     */
    delete(name: string, requestOptions?: Services.RequestOptions): Promise<void>;
    /**
     * Returns basic info about all registered services.
     *
     * For performance reasons, tool details are omitted from the response.
     * Use the retrieve endpoint to get complete information including
     * tools for a specific service.
     *
     * @param {Services.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.services.list()
     */
    list(requestOptions?: Services.RequestOptions): Promise<Parlant.Service[]>;
}
