/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         value: "Your updated balance is {balance}",
 *         fields: [{
 *                 name: "balance",
 *                 description: "Updated account balance",
 *                 examples: ["10000"]
 *             }],
 *         metadata: {
 *             set: {
 *                 "category": "account",
 *                 "priority": 2
 *             },
 *             unset: ["old_field"]
 *         }
 *     }
 */
export interface CannedResponseUpdateParams {
    /** The textual content of the canned response. */
    value?: string;
    /** A sequence of canned response fields associated with the canned response. */
    fields?: Parlant.CannedResponseField[];
    tags?: Parlant.CannedResponseTagUpdateParams;
    metadata?: Parlant.CannedResponseMetadataUpdateParams;
}
