/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         value: "Your account balance is {balance}",
 *         fields: [{
 *                 name: "balance",
 *                 description: "Account's balance",
 *                 examples: ["9000"]
 *             }],
 *         metadata: {
 *             "category": "account",
 *             "priority": 1
 *         },
 *         fieldDependencies: ["account"]
 *     }
 */
export interface CannedResponseCreationParams {
    /** The textual content of the canned response. */
    value: string;
    /** A sequence of canned response fields associated with the canned response. */
    fields: Parlant.CannedResponseField[];
    /** Collection of tag IDs associated with the canned response. */
    tags?: string[];
    /** A sequence of signals associated with the canned response, to help with filtering and matching. */
    signals?: string[];
    /** Additional metadata associated with the canned response. */
    metadata?: Record<string, unknown>;
    /** A sequence of field names that must be available in context for this response to be considered. */
    fieldDependencies?: string[];
}
