/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { CannedResponseField } from "../../../../types/CannedResponseField";
import { CannedResponseTagUpdateParams } from "../../../../types/CannedResponseTagUpdateParams";
import { CannedResponseMetadataUpdateParams } from "../../../../types/CannedResponseMetadataUpdateParams";
export declare const CannedResponseUpdateParams: core.serialization.Schema<serializers.CannedResponseUpdateParams.Raw, Parlant.CannedResponseUpdateParams>;
export declare namespace CannedResponseUpdateParams {
    interface Raw {
        value?: string | null;
        fields?: CannedResponseField.Raw[] | null;
        tags?: CannedResponseTagUpdateParams.Raw | null;
        metadata?: CannedResponseMetadataUpdateParams.Raw | null;
    }
}
