/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { CannedResponseField } from "../../../../types/CannedResponseField";
export declare const CannedResponseCreationParams: core.serialization.Schema<serializers.CannedResponseCreationParams.Raw, Parlant.CannedResponseCreationParams>;
export declare namespace CannedResponseCreationParams {
    interface Raw {
        value: string;
        fields: CannedResponseField.Raw[];
        tags?: string[] | null;
        signals?: string[] | null;
        metadata?: Record<string, unknown> | null;
        field_dependencies?: string[] | null;
    }
}
