/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { Payload } from "../../../../types/Payload";
export declare const EvaluationCreationParams: core.serialization.Schema<serializers.EvaluationCreationParams.Raw, Parlant.EvaluationCreationParams>;
export declare namespace EvaluationCreationParams {
    interface Raw {
        payloads: Payload.Raw[];
    }
}
