/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Parlant from "../../../../api/index";
import * as core from "../../../../core";
import { PaginatedCustomers } from "../../../types/PaginatedCustomers";
import { Customer } from "../../../types/Customer";
export declare const CustomersListResponse: core.serialization.Schema<serializers.CustomersListResponse.Raw, Parlant.CustomersListResponse>;
export declare namespace CustomersListResponse {
    type Raw = PaginatedCustomers.Raw | Customer.Raw[];
}
