/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as Parlant from "../../../index";
export declare namespace Guidelines {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Guidelines {
    protected readonly _options: Guidelines.Options;
    constructor(_options: Guidelines.Options);
    /**
     * Lists all guidelines for the specified tag or all guidelines if no tag is provided.
     *
     * Returns an empty list if no guidelines exist.
     * Guidelines are returned in no guaranteed order.
     * Does not include relationships or tool associations.
     *
     * @param {Parlant.GuidelinesListRequest} request
     * @param {Guidelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.guidelines.list()
     */
    list(request?: Parlant.GuidelinesListRequest, requestOptions?: Guidelines.RequestOptions): Promise<Parlant.Guideline[]>;
    /**
     * Creates a new guideline.
     *
     * The guideline will be initialized with the provided condition and optional action and settings.
     * A unique identifier will be automatically generated unless a custom ID is provided.
     *
     * See the [documentation](https://parlant.io/docs/concepts/customization/guidelines) for more information.
     *
     * @param {Parlant.GuidelineCreationParams} request
     * @param {Guidelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.guidelines.create({
     *         condition: "when the customer asks about pricing",
     *         action: "provide current pricing information and mention any ongoing promotions",
     *         metadata: {
     *             "key1": "value1",
     *             "key2": "value2"
     *         },
     *         enabled: false,
     *         compositionMode: "strict_canned",
     *         labels: ["vip", "priority"]
     *     })
     */
    create(request: Parlant.GuidelineCreationParams, requestOptions?: Guidelines.RequestOptions): Promise<Parlant.Guideline>;
    /**
     * Retrieves a specific guideline with all its relationships and tool associations.
     *
     * Returns both direct and indirect relationships between guidelines.
     * Tool associations indicate which tools the guideline can use.
     *
     * @param {string} guidelineId - Unique identifier for the guideline
     * @param {Guidelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.guidelines.retrieve("IUCGT-l4pS")
     */
    retrieve(guidelineId: string, requestOptions?: Guidelines.RequestOptions): Promise<Parlant.GuidelineWithRelationshipsAndToolAssociations>;
    /**
     * @param {string} guidelineId - Unique identifier for the guideline
     * @param {Guidelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.guidelines.delete("IUCGT-l4pS")
     */
    delete(guidelineId: string, requestOptions?: Guidelines.RequestOptions): Promise<void>;
    /**
     * Updates a guideline's relationships and tool associations.
     *
     * Only provided attributes will be updated; others remain unchanged.
     *
     * Relationship rules:
     * - A guideline cannot relate to itself
     * - Only direct relationships can be removed
     * - The relationship must specify this guideline as source or target
     *
     * Tool Association rules:
     * - Tool services and tools must exist before creating associations
     *
     * Action with text can not be updated to None.
     *
     * @param {string} guidelineId - Unique identifier for the guideline
     * @param {Parlant.GuidelineUpdateParams} request
     * @param {Guidelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.guidelines.update("IUCGT-l4pS", {
     *         condition: "when the customer asks about pricing",
     *         action: "provide current pricing information",
     *         toolAssociations: {
     *             add: [{
     *                     serviceName: "new_service",
     *                     toolName: "new_tool"
     *                 }],
     *             remove: [{
     *                     serviceName: "old_service",
     *                     toolName: "old_tool"
     *                 }]
     *         },
     *         enabled: true,
     *         metadata: {
     *             set: {
     *                 "key1": "value1",
     *                 "key2": "value2"
     *             },
     *             unset: ["key3", "key4"]
     *         }
     *     })
     */
    update(guidelineId: string, request?: Parlant.GuidelineUpdateParams, requestOptions?: Guidelines.RequestOptions): Promise<Parlant.GuidelineWithRelationshipsAndToolAssociations>;
}
