/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         name: "Scooby",
 *         tags: {
 *             add: ["t9a8g703f4", "tag_456abc"],
 *             remove: ["tag_789def", "tag_012ghi"]
 *         }
 *     }
 */
export interface CustomerUpdateParams {
    /** An arbitrary string that identifies and/or describes the customer */
    name?: string;
    metadata?: Parlant.CustomerMetadataUpdateParams;
    tags?: Parlant.CustomerTagUpdateParams;
}
