/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         limit: 10,
 *         cursor: "AAABjnBU9gBl/0BQt1axI0VniQI="
 *     }
 */
export interface CustomersListRequest {
    limit?: number;
    cursor?: string;
    sort?: Parlant.SortDirectionDto;
}
