/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Parlant from "../../../../api/index";
import * as core from "../../../../core";
import { Agent } from "../../../types/Agent";
export declare const Response: core.serialization.Schema<serializers.agents.list.Response.Raw, Parlant.Agent[]>;
export declare namespace Response {
    type Raw = Agent.Raw[];
}
