/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "./core";
import { Agents } from "./api/resources/agents/client/Client";
import { Sessions } from "./api/resources/sessions/client/Client";
import { Services } from "./api/resources/services/client/Client";
import { Tags } from "./api/resources/tags/client/Client";
import { Glossary } from "./api/resources/glossary/client/Client";
import { Customers } from "./api/resources/customers/client/Client";
import { CannedResponses } from "./api/resources/cannedResponses/client/Client";
import { ContextVariables } from "./api/resources/contextVariables/client/Client";
import { Guidelines } from "./api/resources/guidelines/client/Client";
import { Relationships } from "./api/resources/relationships/client/Client";
import { Journeys } from "./api/resources/journeys/client/Client";
import { Evaluations } from "./api/resources/evaluations/client/Client";
import { Capabilities } from "./api/resources/capabilities/client/Client";
export declare namespace ParlantClient {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class ParlantClient {
    protected readonly _options: ParlantClient.Options;
    protected _agents: Agents | undefined;
    protected _sessions: Sessions | undefined;
    protected _services: Services | undefined;
    protected _tags: Tags | undefined;
    protected _glossary: Glossary | undefined;
    protected _customers: Customers | undefined;
    protected _cannedResponses: CannedResponses | undefined;
    protected _contextVariables: ContextVariables | undefined;
    protected _guidelines: Guidelines | undefined;
    protected _relationships: Relationships | undefined;
    protected _journeys: Journeys | undefined;
    protected _evaluations: Evaluations | undefined;
    protected _capabilities: Capabilities | undefined;
    constructor(_options: ParlantClient.Options);
    get agents(): Agents;
    get sessions(): Sessions;
    get services(): Services;
    get tags(): Tags;
    get glossary(): Glossary;
    get customers(): Customers;
    get cannedResponses(): CannedResponses;
    get contextVariables(): ContextVariables;
    get guidelines(): Guidelines;
    get relationships(): Relationships;
    get journeys(): Journeys;
    get evaluations(): Evaluations;
    get capabilities(): Capabilities;
    /**
     * @param {ParlantClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.healthCheckHealthzGet()
     */
    healthCheckHealthzGet(requestOptions?: ParlantClient.RequestOptions): Promise<Record<string, unknown>>;
}
