/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as Parlant from "../../../index";
export declare namespace CannedResponses {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class CannedResponses {
    protected readonly _options: CannedResponses.Options;
    constructor(_options: CannedResponses.Options);
    /**
     * Lists all canned responses, optionally filtered by tags.
     *
     * @param {Parlant.CannedResponsesListRequest} request
     * @param {CannedResponses.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.cannedResponses.list()
     */
    list(request?: Parlant.CannedResponsesListRequest, requestOptions?: CannedResponses.RequestOptions): Promise<Parlant.CannedResponse[]>;
    /**
     * @param {Parlant.CannedResponseCreationParams} request
     * @param {CannedResponses.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.cannedResponses.create({
     *         value: "Your account balance is {balance}",
     *         fields: [{
     *                 name: "balance",
     *                 description: "Account's balance",
     *                 examples: ["9000"]
     *             }],
     *         metadata: {
     *             "category": "account",
     *             "priority": 1
     *         },
     *         fieldDependencies: ["account"]
     *     })
     */
    create(request: Parlant.CannedResponseCreationParams, requestOptions?: CannedResponses.RequestOptions): Promise<Parlant.CannedResponse>;
    /**
     * Retrieves details of a specific canned response by ID.
     *
     * @param {string} cannedResponseId
     * @param {CannedResponses.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.cannedResponses.retrieve("t9a8g703f4")
     */
    retrieve(cannedResponseId: string, requestOptions?: CannedResponses.RequestOptions): Promise<Parlant.CannedResponse>;
    /**
     * @param {string} cannedResponseId
     * @param {CannedResponses.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.cannedResponses.delete("t9a8g703f4")
     */
    delete(cannedResponseId: string, requestOptions?: CannedResponses.RequestOptions): Promise<void>;
    /**
     * Updates an existing canned response's attributes.
     *
     * Only provided attributes will be updated; others remain unchanged.
     * The canned response's ID and creation timestamp cannot be modified.
     * Extra metadata and tags can be added or removed independently.
     *
     * @param {string} cannedResponseId
     * @param {Parlant.CannedResponseUpdateParams} request
     * @param {CannedResponses.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.cannedResponses.update("t9a8g703f4", {
     *         value: "Your updated balance is {balance}",
     *         fields: [{
     *                 name: "balance",
     *                 description: "Updated account balance",
     *                 examples: ["10000"]
     *             }],
     *         metadata: {
     *             set: {
     *                 "category": "account",
     *                 "priority": 2
     *             },
     *             unset: ["old_field"]
     *         }
     *     })
     */
    update(cannedResponseId: string, request?: Parlant.CannedResponseUpdateParams, requestOptions?: CannedResponses.RequestOptions): Promise<Parlant.CannedResponse>;
}
