/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         condition: "when the customer asks about pricing",
 *         action: "provide current pricing information and mention any ongoing promotions",
 *         metadata: {
 *             "key1": "value1",
 *             "key2": "value2"
 *         },
 *         enabled: false,
 *         compositionMode: "strict_canned",
 *         labels: ["vip", "priority"]
 *     }
 */
export interface GuidelineCreationParams {
    /** Unique identifier for the guideline */
    id?: string;
    /** If this condition is satisfied, the action will be performed */
    condition: string;
    /** This action will be performed if the condition is satisfied */
    action?: string;
    /** Optional description providing additional context for the guideline */
    description?: string;
    criticality?: Parlant.CriticalityDto;
    /** Metadata for the guideline */
    metadata?: Record<string, unknown>;
    /** Whether the guideline is enabled */
    enabled?: boolean;
    /** The tags associated with the guideline */
    tags?: string[];
    compositionMode?: Parlant.CompositionModeDto;
    track?: boolean;
    /** The labels associated with the guideline */
    labels?: string[];
    priority?: number;
}
