/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface CapabilitiesListRequest {
    /**
     * The tag ID to filter capabilities by
     */
    tagId?: string;
}
