/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         title: "Provide Replacement Phone",
 *         description: "Provide a replacement phone when a customer needs repair for their phone.",
 *         signals: ["My phone is broken", "I need a replacement while my phone is being repaired"]
 *     }
 */
export interface CapabilityUpdateParams {
    /** The title of the capability */
    title?: string;
    /** Detailed description of the capability's purpose */
    description?: string;
    /** Example signals that this capability can handle */
    signals?: string[];
    tags?: Parlant.CapabilityTagUpdateParams;
}
