/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const AgentMessageGuidelineRationaleDto: core.serialization.Schema<serializers.AgentMessageGuidelineRationaleDto.Raw, Parlant.AgentMessageGuidelineRationaleDto>;
export declare namespace AgentMessageGuidelineRationaleDto {
    type Raw = "unspecified" | "buy_time" | "follow_up";
}
