/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { AgentMessageGuidelineRationaleDto } from "./AgentMessageGuidelineRationaleDto";
export declare const AgentMessageGuideline: core.serialization.ObjectSchema<serializers.AgentMessageGuideline.Raw, Parlant.AgentMessageGuideline>;
export declare namespace AgentMessageGuideline {
    interface Raw {
        action: string;
        rationale?: AgentMessageGuidelineRationaleDto.Raw | null;
    }
}
