/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const CannedResponseTagUpdateParams: core.serialization.ObjectSchema<serializers.CannedResponseTagUpdateParams.Raw, Parlant.CannedResponseTagUpdateParams>;
export declare namespace CannedResponseTagUpdateParams {
    interface Raw {
        add?: string[] | null;
        remove?: string[] | null;
    }
}
