/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { CannedResponseField } from "./CannedResponseField";
export declare const CannedResponse: core.serialization.ObjectSchema<serializers.CannedResponse.Raw, Parlant.CannedResponse>;
export declare namespace CannedResponse {
    interface Raw {
        id: string;
        creation_utc: string;
        value: string;
        fields: CannedResponseField.Raw[];
        tags: string[];
        signals: string[];
        metadata: Record<string, unknown>;
        field_dependencies?: string[] | null;
    }
}
