/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const CannedResponseMetadataUpdateParams: core.serialization.ObjectSchema<serializers.CannedResponseMetadataUpdateParams.Raw, Parlant.CannedResponseMetadataUpdateParams>;
export declare namespace CannedResponseMetadataUpdateParams {
    interface Raw {
        set?: Record<string, unknown> | null;
        unset?: string[] | null;
    }
}
