/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const CannedResponseField: core.serialization.ObjectSchema<serializers.CannedResponseField.Raw, Parlant.CannedResponseField>;
export declare namespace CannedResponseField {
    interface Raw {
        name: string;
        description: string;
        examples: string[];
    }
}
