/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const Capability: core.serialization.ObjectSchema<serializers.Capability.Raw, Parlant.Capability>;
export declare namespace Capability {
    interface Raw {
        id: string;
        title: string;
        description: string;
        signals: string[];
        tags?: string[] | null;
    }
}
