/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const CapabilityTagUpdateParams: core.serialization.ObjectSchema<serializers.CapabilityTagUpdateParams.Raw, Parlant.CapabilityTagUpdateParams>;
export declare namespace CapabilityTagUpdateParams {
    interface Raw {
        add?: string[] | null;
        remove?: string[] | null;
    }
}
