/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const CompositionModeDto: core.serialization.Schema<serializers.CompositionModeDto.Raw, Parlant.CompositionModeDto>;
export declare namespace CompositionModeDto {
    type Raw = "fluid" | "canned_fluid" | "composited_canned" | "strict_canned";
}
