/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const ConsumptionOffsets: core.serialization.ObjectSchema<serializers.ConsumptionOffsets.Raw, Parlant.ConsumptionOffsets>;
export declare namespace ConsumptionOffsets {
    interface Raw {
        client?: number | null;
    }
}
