/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const ConsumptionOffsetsUpdateParams: core.serialization.ObjectSchema<serializers.ConsumptionOffsetsUpdateParams.Raw, Parlant.ConsumptionOffsetsUpdateParams>;
export declare namespace ConsumptionOffsetsUpdateParams {
    interface Raw {
        client?: number | null;
    }
}
