/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { ToolId } from "./ToolId";
export declare const ContextVariable: core.serialization.ObjectSchema<serializers.ContextVariable.Raw, Parlant.ContextVariable>;
export declare namespace ContextVariable {
    interface Raw {
        id: string;
        name: string;
        description?: string | null;
        tool_id?: ToolId.Raw | null;
        freshness_rules?: string | null;
        tags?: string[] | null;
    }
}
