/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const ContextVariableValue: core.serialization.ObjectSchema<serializers.ContextVariableValue.Raw, Parlant.ContextVariableValue>;
export declare namespace ContextVariableValue {
    interface Raw {
        id: string;
        last_modified: string;
        data?: unknown;
    }
}
