/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const CriticalityDto: core.serialization.Schema<serializers.CriticalityDto.Raw, Parlant.CriticalityDto>;
export declare namespace CriticalityDto {
    type Raw = "low" | "medium" | "high";
}
