/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const CustomerMetadataUpdateParams: core.serialization.ObjectSchema<serializers.CustomerMetadataUpdateParams.Raw, Parlant.CustomerMetadataUpdateParams>;
export declare namespace CustomerMetadataUpdateParams {
    interface Raw {
        set?: Record<string, string | null | undefined> | null;
        unset?: string[] | null;
    }
}
