/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const CustomerTagUpdateParams: core.serialization.ObjectSchema<serializers.CustomerTagUpdateParams.Raw, Parlant.CustomerTagUpdateParams>;
export declare namespace CustomerTagUpdateParams {
    interface Raw {
        add?: string[] | null;
        remove?: string[] | null;
    }
}
