/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const EventKindDto: core.serialization.Schema<serializers.EventKindDto.Raw, Parlant.EventKindDto>;
export declare namespace EventKindDto {
    type Raw = "message" | "tool" | "status" | "custom";
}
