/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const GuidelineLabelsUpdateParams: core.serialization.ObjectSchema<serializers.GuidelineLabelsUpdateParams.Raw, Parlant.GuidelineLabelsUpdateParams>;
export declare namespace GuidelineLabelsUpdateParams {
    interface Raw {
        upsert?: string[] | null;
        remove?: string[] | null;
    }
}
