/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const GuidelineMetadataUpdateParams: core.serialization.ObjectSchema<serializers.GuidelineMetadataUpdateParams.Raw, Parlant.GuidelineMetadataUpdateParams>;
export declare namespace GuidelineMetadataUpdateParams {
    interface Raw {
        set?: Record<string, unknown> | null;
        unset?: string[] | null;
    }
}
