/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const GuidelineTagsUpdateParams: core.serialization.ObjectSchema<serializers.GuidelineTagsUpdateParams.Raw, Parlant.GuidelineTagsUpdateParams>;
export declare namespace GuidelineTagsUpdateParams {
    interface Raw {
        add?: string[] | null;
        remove?: string[] | null;
    }
}
