/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { Guideline } from "./Guideline";
import { Relationship } from "./Relationship";
import { GuidelineToolAssociation } from "./GuidelineToolAssociation";
export declare const GuidelineWithRelationshipsAndToolAssociations: core.serialization.ObjectSchema<serializers.GuidelineWithRelationshipsAndToolAssociations.Raw, Parlant.GuidelineWithRelationshipsAndToolAssociations>;
export declare namespace GuidelineWithRelationshipsAndToolAssociations {
    interface Raw {
        guideline: Guideline.Raw;
        relationships: Relationship.Raw[];
        tool_associations: GuidelineToolAssociation.Raw[];
    }
}
