/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const GuidelineInvoiceData: core.serialization.ObjectSchema<serializers.GuidelineInvoiceData.Raw, Parlant.GuidelineInvoiceData>;
export declare namespace GuidelineInvoiceData {
    interface Raw {
        action_proposition?: string | null;
        properties_proposition?: Record<string, unknown> | null;
    }
}
