/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const GuidelineContent: core.serialization.ObjectSchema<serializers.GuidelineContent.Raw, Parlant.GuidelineContent>;
export declare namespace GuidelineContent {
    interface Raw {
        condition: string;
        action?: string | null;
    }
}
