/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const GuidelinePayloadOperationDto: core.serialization.Schema<serializers.GuidelinePayloadOperationDto.Raw, Parlant.GuidelinePayloadOperationDto>;
export declare namespace GuidelinePayloadOperationDto {
    type Raw = "add" | "update";
}
