/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { Payload } from "./Payload";
import { InvoiceData } from "./InvoiceData";
export declare const Invoice: core.serialization.ObjectSchema<serializers.Invoice.Raw, Parlant.Invoice>;
export declare namespace Invoice {
    interface Raw {
        payload: Payload.Raw;
        checksum: string;
        approved: boolean;
        data?: InvoiceData.Raw | null;
        error?: string | null;
    }
}
