/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { GuidelineInvoiceData } from "./GuidelineInvoiceData";
export declare const InvoiceData: core.serialization.ObjectSchema<serializers.InvoiceData.Raw, Parlant.InvoiceData>;
export declare namespace InvoiceData {
    interface Raw {
        guideline?: GuidelineInvoiceData.Raw | null;
    }
}
