/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const JourneyLabelsUpdateParams: core.serialization.ObjectSchema<serializers.JourneyLabelsUpdateParams.Raw, Parlant.JourneyLabelsUpdateParams>;
export declare namespace JourneyLabelsUpdateParams {
    interface Raw {
        upsert?: string[] | null;
        remove?: string[] | null;
    }
}
