/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const JourneyConditionUpdateParams: core.serialization.ObjectSchema<serializers.JourneyConditionUpdateParams.Raw, Parlant.JourneyConditionUpdateParams>;
export declare namespace JourneyConditionUpdateParams {
    interface Raw {
        add?: string[] | null;
        remove?: string[] | null;
    }
}
