/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { CompositionModeDto } from "./CompositionModeDto";
export declare const Journey: core.serialization.ObjectSchema<serializers.Journey.Raw, Parlant.Journey>;
export declare namespace Journey {
    interface Raw {
        id: string;
        title: string;
        description: string;
        conditions: string[];
        tags?: string[] | null;
        composition_mode?: CompositionModeDto.Raw | null;
        labels?: string[] | null;
        priority?: number | null;
    }
}
