/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const McpServiceParams: core.serialization.ObjectSchema<serializers.McpServiceParams.Raw, Parlant.McpServiceParams>;
export declare namespace McpServiceParams {
    interface Raw {
        url: string;
    }
}
