/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const MessageOutputModeDto: core.serialization.Schema<serializers.MessageOutputModeDto.Raw, Parlant.MessageOutputModeDto>;
export declare namespace MessageOutputModeDto {
    type Raw = "block" | "stream";
}
