/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const OpenApiServiceParams: core.serialization.ObjectSchema<serializers.OpenApiServiceParams.Raw, Parlant.OpenApiServiceParams>;
export declare namespace OpenApiServiceParams {
    interface Raw {
        url: string;
        source: string;
    }
}
