/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { Customer } from "./Customer";
export declare const PaginatedCustomers: core.serialization.ObjectSchema<serializers.PaginatedCustomers.Raw, Parlant.PaginatedCustomers>;
export declare namespace PaginatedCustomers {
    interface Raw {
        items: Customer.Raw[];
        total_count: number;
        has_more: boolean;
        next_cursor?: string | null;
    }
}
