/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const Participant: core.serialization.ObjectSchema<serializers.Participant.Raw, Parlant.Participant>;
export declare namespace Participant {
    interface Raw {
        id?: string | null;
        display_name: string;
    }
}
