/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const PayloadKindDto: core.serialization.Schema<serializers.PayloadKindDto.Raw, Parlant.PayloadKindDto>;
export declare namespace PayloadKindDto {
    type Raw = "guideline";
}
