/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { PayloadKindDto } from "./PayloadKindDto";
import { GuidelinePayload } from "./GuidelinePayload";
export declare const Payload: core.serialization.ObjectSchema<serializers.Payload.Raw, Parlant.Payload>;
export declare namespace Payload {
    interface Raw {
        kind: PayloadKindDto.Raw;
        guideline?: GuidelinePayload.Raw | null;
    }
}
