/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const SdkServiceParams: core.serialization.ObjectSchema<serializers.SdkServiceParams.Raw, Parlant.SdkServiceParams>;
export declare namespace SdkServiceParams {
    interface Raw {
        url: string;
    }
}
