/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { ToolServiceKindDto } from "./ToolServiceKindDto";
import { Tool } from "./Tool";
export declare const Service: core.serialization.ObjectSchema<serializers.Service.Raw, Parlant.Service>;
export declare namespace Service {
    interface Raw {
        name: string;
        kind: ToolServiceKindDto.Raw;
        url: string;
        tools?: Tool.Raw[] | null;
    }
}
