/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const SessionMetadataUpdateParams: core.serialization.ObjectSchema<serializers.SessionMetadataUpdateParams.Raw, Parlant.SessionMetadataUpdateParams>;
export declare namespace SessionMetadataUpdateParams {
    interface Raw {
        set?: Record<string, unknown> | null;
        unset?: string[] | null;
    }
}
