/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const SessionLabelsUpdateParams: core.serialization.ObjectSchema<serializers.SessionLabelsUpdateParams.Raw, Parlant.SessionLabelsUpdateParams>;
export declare namespace SessionLabelsUpdateParams {
    interface Raw {
        upsert?: string[] | null;
        remove?: string[] | null;
    }
}
