/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const SessionModeDto: core.serialization.Schema<serializers.SessionModeDto.Raw, Parlant.SessionModeDto>;
export declare namespace SessionModeDto {
    type Raw = "auto" | "manual";
}
