/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { SessionModeDto } from "./SessionModeDto";
import { ConsumptionOffsets } from "./ConsumptionOffsets";
export declare const Session: core.serialization.ObjectSchema<serializers.Session.Raw, Parlant.Session>;
export declare namespace Session {
    interface Raw {
        id: string;
        agent_id: string;
        customer_id: string;
        creation_utc: string;
        title?: string | null;
        mode: SessionModeDto.Raw;
        consumption_offsets: ConsumptionOffsets.Raw;
        metadata: Record<string, unknown>;
        labels?: string[] | null;
    }
}
