/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { Session } from "./Session";
export declare const SessionListing: core.serialization.ObjectSchema<serializers.SessionListing.Raw, Parlant.SessionListing>;
export declare namespace SessionListing {
    interface Raw {
        items: Session.Raw[];
        total_count: number;
        has_more: boolean;
        next_cursor?: string | null;
    }
}
