/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const SortDirectionDto: core.serialization.Schema<serializers.SortDirectionDto.Raw, Parlant.SortDirectionDto>;
export declare namespace SortDirectionDto {
    type Raw = "asc" | "desc";
}
