/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const Tag: core.serialization.ObjectSchema<serializers.Tag.Raw, Parlant.Tag>;
export declare namespace Tag {
    interface Raw {
        id: string;
        name: string;
    }
}
