/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const ToolParameterDtoEnumItem: core.serialization.Schema<serializers.ToolParameterDtoEnumItem.Raw, Parlant.ToolParameterDtoEnumItem>;
export declare namespace ToolParameterDtoEnumItem {
    type Raw = string | number;
}
