/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const ToolServiceKindDto: core.serialization.Schema<serializers.ToolServiceKindDto.Raw, Parlant.ToolServiceKindDto>;
export declare namespace ToolServiceKindDto {
    type Raw = "sdk" | "openapi" | "mcp";
}
