/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const ToolId: core.serialization.ObjectSchema<serializers.ToolId.Raw, Parlant.ToolId>;
export declare namespace ToolId {
    interface Raw {
        service_name: string;
        tool_name: string;
    }
}
