/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const ToolParameterTypeDto: core.serialization.Schema<serializers.ToolParameterTypeDto.Raw, Parlant.ToolParameterTypeDto>;
export declare namespace ToolParameterTypeDto {
    type Raw = "string" | "number" | "integer" | "boolean" | "array";
}
