/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { ToolParameterTypeDto } from "./ToolParameterTypeDto";
import { ToolParameterDtoEnumItem } from "./ToolParameterDtoEnumItem";
export declare const ToolParameter: core.serialization.ObjectSchema<serializers.ToolParameter.Raw, Parlant.ToolParameter>;
export declare namespace ToolParameter {
    interface Raw {
        type: ToolParameterTypeDto.Raw;
        description?: string | null;
        enum?: ToolParameterDtoEnumItem.Raw[] | null;
    }
}
