/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { ToolParameter } from "./ToolParameter";
export declare const Tool: core.serialization.ObjectSchema<serializers.Tool.Raw, Parlant.Tool>;
export declare namespace Tool {
    interface Raw {
        creation_utc: string;
        name: string;
        description: string;
        parameters: Record<string, ToolParameter.Raw>;
        required: string[];
    }
}
