/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const ValidationErrorLocItem: core.serialization.Schema<serializers.ValidationErrorLocItem.Raw, Parlant.ValidationErrorLocItem>;
export declare namespace ValidationErrorLocItem {
    type Raw = string | number;
}
