/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as Parlant from "../../../index";
export declare namespace Sessions {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Sessions {
    protected readonly _options: Sessions.Options;
    constructor(_options: Sessions.Options);
    /**
     * Lists all sessions matching the specified filters with pagination support.
     *
     * Can filter by agent_id and/or customer_id. Supports cursor-based pagination
     * with configurable sort direction.
     *
     * @param {Parlant.SessionsListRequest} request
     * @param {Sessions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.sessions.list({
     *         agentId: "ag_123xyz",
     *         customerId: "cust_123xy",
     *         limit: 10,
     *         cursor: "AAABjnBU9gBl/0BQt1axI0VniQI="
     *     })
     */
    list(request?: Parlant.SessionsListRequest, requestOptions?: Sessions.RequestOptions): Promise<Parlant.SessionsListResponse>;
    /**
     * Creates a new session between an agent and customer.
     *
     * The session will be initialized with the specified agent and optional customer.
     * If no customer_id is provided, a guest customer will be created.
     *
     * @param {Parlant.SessionCreationParams} request
     * @param {Sessions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.sessions.create({
     *         agentId: "ag_123xyz",
     *         customerId: "cust_123xy",
     *         title: "Product inquiry session",
     *         metadata: {
     *             "priority": "high",
     *             "project": "demo"
     *         },
     *         labels: ["vip", "priority"]
     *     })
     */
    create(request: Parlant.SessionCreationParams, requestOptions?: Sessions.RequestOptions): Promise<Parlant.Session>;
    /**
     * Deletes all sessions matching the specified filters.
     *
     * Can filter by agent_id and/or customer_id. Will delete all sessions if no
     * filters are provided.
     *
     * @param {Parlant.SessionsDeleteManyRequest} request
     * @param {Sessions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.sessions.deleteMany({
     *         agentId: "ag_123xyz",
     *         customerId: "cust_123xy"
     *     })
     */
    deleteMany(request?: Parlant.SessionsDeleteManyRequest, requestOptions?: Sessions.RequestOptions): Promise<void>;
    /**
     * Retrieves details of a specific session by ID.
     *
     * @param {string} sessionId - Unique identifier for the session
     * @param {Sessions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.sessions.retrieve("sess_123yz")
     */
    retrieve(sessionId: string, requestOptions?: Sessions.RequestOptions): Promise<Parlant.Session>;
    /**
     * Deletes a session and all its associated events.
     *
     * The operation is idempotent - deleting a non-existent session will return 404.
     *
     * @param {string} sessionId - Unique identifier for the session
     * @param {Sessions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.sessions.delete("sess_123yz")
     */
    delete(sessionId: string, requestOptions?: Sessions.RequestOptions): Promise<void>;
    /**
     * Updates an existing session's attributes.
     *
     * Only provided attributes will be updated; others remain unchanged.
     *
     * @param {string} sessionId - Unique identifier for the session
     * @param {Parlant.SessionUpdateParams} request
     * @param {Sessions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.sessions.update("sess_123yz", {
     *         consumptionOffsets: {
     *             client: 42
     *         },
     *         title: "Updated session title",
     *         metadata: {
     *             set: {
     *                 "priority": "low",
     *                 "simulation": true
     *             },
     *             unset: ["old_project"]
     *         },
     *         labels: {
     *             upsert: ["vip", "priority"],
     *             remove: ["old_label"]
     *         }
     *     })
     */
    update(sessionId: string, request?: Parlant.SessionUpdateParams, requestOptions?: Sessions.RequestOptions): Promise<Parlant.Session>;
    /**
     * Lists events from a session with optional filtering and waiting capabilities.
     *
     * This endpoint retrieves events from a specified session and can:
     * 1. Filter events by their offset, source, type, and trace ID
     * 2. Wait for new events to arrive if requested
     * 3. Return events in chronological order based on their offset
     * 4. Stream events via Server-Sent Events (SSE) when sse=true
     *
     * Notes:
     *     Long Polling Behavior (when sse=false):
     *     - When wait_for_data = 0:
     *         Returns immediately with any existing events that match the criteria
     *     - When wait_for_data > 0:
     *         - If new matching events arrive within the timeout period, returns with those events
     *         - If no new events arrive before timeout, raises 504 Gateway Timeout
     *         - If matching events already exist, returns immediately with those events
     *
     *     SSE Mode (when sse=true):
     *     - Returns a text/event-stream response
     *     - Continuously sends events as they arrive
     *     - wait_for_data is used as the timeout between events before closing the stream
     *
     * @param {string} sessionId - Unique identifier for the session
     * @param {Parlant.SessionsListEventsRequest} request
     * @param {Sessions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     * @throws {@link Parlant.GatewayTimeoutError}
     *
     * @example
     *     await client.sessions.listEvents("sess_123yz", {
     *         minOffset: 0,
     *         correlationId: "corr_13xyz",
     *         traceId: "corr_13xyz",
     *         kinds: "message,tool"
     *     })
     */
    listEvents(sessionId: string, request?: Parlant.SessionsListEventsRequest, requestOptions?: Sessions.RequestOptions): Promise<Parlant.Event[]>;
    /**
     * Creates a new event in the specified session.
     *
     * Currently supports creating message events from customer and human agent sources.
     *
     * @param {string} sessionId - Unique identifier for the session
     * @param {Parlant.EventCreationParams} request
     * @param {Sessions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.sessions.createEvent("sess_123yz", {
     *         kind: "message",
     *         source: "customer",
     *         message: "Hello, I need help with my order"
     *     })
     */
    createEvent(sessionId: string, request: Parlant.EventCreationParams, requestOptions?: Sessions.RequestOptions): Promise<Parlant.Event>;
    /**
     * Deletes events from a session with offset >= the specified value.
     *
     * This operation is permanent and cannot be undone.
     *
     * @param {string} sessionId - Unique identifier for the session
     * @param {Parlant.SessionsDeleteEventsRequest} request
     * @param {Sessions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.sessions.deleteEvents("sess_123yz", {
     *         minOffset: 0
     *     })
     */
    deleteEvents(sessionId: string, request: Parlant.SessionsDeleteEventsRequest, requestOptions?: Sessions.RequestOptions): Promise<void>;
    /**
     * Reads a single event from a session.
     *
     * This endpoint retrieves a specific event by its ID and optionally waits
     * for the event to complete (useful for streaming messages).
     *
     * Args:
     *     wait_for_completion: If true, wait for the event to complete (for streaming events,
     *         this means waiting until chunks contains None terminator)
     *     wait_for_data: Timeout in seconds for wait_for_completion
     *     sse: If true, stream event updates via Server-Sent Events until completion
     *
     * Notes:
     *     For streaming message events (events with 'chunks' property):
     *     - The event is considered complete when chunks contains a None terminator
     *     - Use wait_for_completion=true to wait for the full message
     *     - Use sse=true to stream updates as chunks are added
     *
     *     SSE Mode (when sse=true):
     *     - Returns a text/event-stream response
     *     - Sends the event each time it's updated
     *     - Closes when the event is complete (chunks ends with None)
     *
     * @param {string} sessionId - Unique identifier for the session
     * @param {string} eventId - Unique identifier for the event
     * @param {Parlant.SessionsReadEventRequest} request
     * @param {Sessions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.sessions.readEvent("sess_123yz", "evt_123xyz")
     */
    readEvent(sessionId: string, eventId: string, request?: Parlant.SessionsReadEventRequest, requestOptions?: Sessions.RequestOptions): Promise<Parlant.Event>;
    /**
     * Updates an event's properties.
     *
     * Currently only supports updating metadata. Other event properties cannot be modified.
     * This API is designed to be extensible for future event property updates.
     *
     * @param {string} sessionId - Unique identifier for the session
     * @param {string} eventId - Unique identifier for the event
     * @param {Parlant.EventUpdateParams} request
     * @param {Sessions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.sessions.updateEvent("sess_123yz", "evt_123xyz", {
     *         metadata: {
     *             set: {
     *                 "agent_id": "agent_123",
     *                 "category": "support",
     *                 "priority": "high"
     *             },
     *             unset: ["old_priority"]
     *         }
     *     })
     */
    updateEvent(sessionId: string, eventId: string, request?: Parlant.EventUpdateParams, requestOptions?: Sessions.RequestOptions): Promise<Parlant.Event>;
}
