/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as Parlant from "../../../index";
export declare namespace Journeys {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Journeys {
    protected readonly _options: Journeys.Options;
    constructor(_options: Journeys.Options);
    /**
     * Retrieves a list of all journeys in the system.
     *
     * @param {Parlant.JourneysListRequest} request
     * @param {Journeys.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.journeys.list()
     */
    list(request?: Parlant.JourneysListRequest, requestOptions?: Journeys.RequestOptions): Promise<Parlant.Journey[]>;
    /**
     * Creates a new journey in the system.
     *
     * The journey will be initialized with the provided title, description, and conditions.
     * A unique identifier will be automatically generated unless a custom ID is provided.
     *
     * @param {Parlant.JourneyCreationParams} request
     * @param {Journeys.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.journeys.create({
     *         title: "Customer Onboarding",
     *         description: "1. Customer wants to lock their card\n2. Customer reports that their card doesn't work\n3. Customer suspects their card has been stolen",
     *         conditions: ["customer needs unlocking their card", "customer needs help with card"],
     *         id: "IUCGT-lvpS",
     *         tags: ["tag1", "tag2"],
     *         labels: ["vip", "priority"]
     *     })
     */
    create(request: Parlant.JourneyCreationParams, requestOptions?: Journeys.RequestOptions): Promise<Parlant.Journey>;
    /**
     * Retrieves details of a specific journey by ID.
     *
     * @param {string} journeyId - Unique identifier for the journey
     * @param {Journeys.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.journeys.retrieve("IUCGT-lvpS")
     */
    retrieve(journeyId: string, requestOptions?: Journeys.RequestOptions): Promise<Parlant.Journey>;
    /**
     * Deletes a journey from the system.
     *
     * Also deletes the associated guideline.
     * Deleting a non-existent journey will return 404.
     * No content will be returned from a successful deletion.
     *
     * @param {string} journeyId - Unique identifier for the journey
     * @param {Journeys.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.journeys.delete("IUCGT-lvpS")
     */
    delete(journeyId: string, requestOptions?: Journeys.RequestOptions): Promise<void>;
    /**
     * Updates an existing journey's attributes.
     *
     * Only the provided attributes will be updated; others will remain unchanged.
     *
     * @param {string} journeyId - Unique identifier for the journey
     * @param {Parlant.JourneyUpdateParams} request
     * @param {Journeys.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.journeys.update("IUCGT-lvpS", {
     *         title: "Customer Onboarding",
     *         description: "1. Customer wants to lock their card\n2. Customer reports that their card doesn't work\n3. Customer suspects their card has been stolen"
     *     })
     */
    update(journeyId: string, request?: Parlant.JourneyUpdateParams, requestOptions?: Journeys.RequestOptions): Promise<Parlant.Journey>;
    /**
     * Returns the journey as a Mermaid 'stateDiagramv-v2' string.
     * Content-Type: text/plain
     *
     * @param {string} journeyId - Unique identifier for the journey
     * @param {Journeys.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.journeys.mermaid("journey_id")
     */
    mermaid(journeyId: string, requestOptions?: Journeys.RequestOptions): Promise<string>;
}
