/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         name: "premium-customer"
 *     }
 */
export interface TagCreationParams {
    /** Human-readable name for the tag, used for display and organization */
    name: string;
}
