/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface TagsListRequest {
    /**
     * Filter tags by name
     */
    name?: string;
}
