/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         name: "UserBalance",
 *         description: "Stores the account balances of users",
 *         toolId: {
 *             serviceName: "finance_service",
 *             toolName: "balance_checker"
 *         },
 *         freshnessRules: "0 8,20 * * *",
 *         tags: {
 *             add: ["tag:123", "tag:456"],
 *             remove: ["tag:789", "tag:012"]
 *         }
 *     }
 */
export interface ContextVariableUpdateParams {
    /** Name of the context variable */
    name?: string;
    /** Description of the context variable's purpose */
    description?: string;
    toolId?: Parlant.ToolId;
    /** Cron expression defining the freshness rules */
    freshnessRules?: string;
    tags?: Parlant.ContextVariableTagsUpdateParams;
}
