/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         includeValues: true
 *     }
 */
export interface ContextVariablesRetrieveRequest {
    /**
     * Whether to include variable values in the response
     */
    includeValues?: boolean;
}
