/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         data: {
 *             "balance": 5000.5,
 *             "currency": "USD",
 *             "last_transaction": "2024-03-23T15:30:00Z",
 *             "status": "active"
 *         }
 *     }
 */
export interface ContextVariableValueUpdateParams {
    data?: unknown;
}
