/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface EvaluationsRetrieveRequest {
    /**
     * Maximum time in seconds to wait for evaluation completion
     */
    waitForCompletion?: number;
}
