/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         payloads: [{
 *                 kind: "guideline",
 *                 guideline: {
 *                     content: {
 *                         condition: "when customer asks about pricing"
 *                     },
 *                     toolIds: [{
 *                             serviceName: "email_service",
 *                             toolName: "send_email"
 *                         }],
 *                     operation: "add",
 *                     actionProposition: true
 *                 }
 *             }]
 *     }
 */
export interface EvaluationCreationParams {
    payloads: Parlant.Payload[];
}
