/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { JourneyConditionUpdateParams } from "../../../../types/JourneyConditionUpdateParams";
import { JourneyTagUpdateParams } from "../../../../types/JourneyTagUpdateParams";
import { CompositionModeDto } from "../../../../types/CompositionModeDto";
import { JourneyLabelsUpdateParams } from "../../../../types/JourneyLabelsUpdateParams";
export declare const JourneyUpdateParams: core.serialization.Schema<serializers.JourneyUpdateParams.Raw, Parlant.JourneyUpdateParams>;
export declare namespace JourneyUpdateParams {
    interface Raw {
        title?: string | null;
        description?: string | null;
        conditions?: JourneyConditionUpdateParams.Raw | null;
        tags?: JourneyTagUpdateParams.Raw | null;
        composition_mode?: CompositionModeDto.Raw | null;
        labels?: JourneyLabelsUpdateParams.Raw | null;
        priority?: number | null;
    }
}
