/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { CriticalityDto } from "../../../../types/CriticalityDto";
import { GuidelineToolAssociationUpdateParams } from "../../../../types/GuidelineToolAssociationUpdateParams";
import { GuidelineTagsUpdateParams } from "../../../../types/GuidelineTagsUpdateParams";
import { GuidelineMetadataUpdateParams } from "../../../../types/GuidelineMetadataUpdateParams";
import { CompositionModeDto } from "../../../../types/CompositionModeDto";
import { GuidelineLabelsUpdateParams } from "../../../../types/GuidelineLabelsUpdateParams";
export declare const GuidelineUpdateParams: core.serialization.Schema<serializers.GuidelineUpdateParams.Raw, Parlant.GuidelineUpdateParams>;
export declare namespace GuidelineUpdateParams {
    interface Raw {
        condition?: string | null;
        action?: string | null;
        description?: string | null;
        criticality?: CriticalityDto.Raw | null;
        tool_associations?: GuidelineToolAssociationUpdateParams.Raw | null;
        enabled?: boolean | null;
        tags?: GuidelineTagsUpdateParams.Raw | null;
        metadata?: GuidelineMetadataUpdateParams.Raw | null;
        composition_mode?: CompositionModeDto.Raw | null;
        labels?: GuidelineLabelsUpdateParams.Raw | null;
        priority?: number | null;
    }
}
